### ISSUE TITLE
Create SWIG bindings

### ISSUE THREAD

**Issue by qdot** [openyou/libomron#1]
Create SWIG bindings so that data is retrievable from Java.

**Comment by brettviren** [comment]
Of course I ticket see this _after_ spending the weekend doing just this.  Ha!  

The swig/ subdirectory in my fork should be able to add Java or other languages by replicating the last 3 lines in swig/CMakeLists.txt for the language in question.

**Comment by qdot** [comment]
Considering this fixed.
