### ISSUE TITLE
Unknown CMake Command "BUILDSYS_BUILD_LIB"

### ISSUE THREAD

**Issue by JoshHrach** [openyou/libomron#15]
I saw others have this issue, but I'm not sure if their solutions would be the same for me.

I'm developing on a Windows XP machine. I downloaded the libomron-0.9.0 package and have that extracted. I also installed all of the required components (WDK, CMake). I follow the instructions provided at http://sourceforge.net/projects/nplabs/files/libomron/0.9.0/ but am getting the above mentioned problem.

Are there further instructions besides those provided at the link?

I don't have git configured on the machine I'm developing on, but would those steps assist me in solving this issue? Or is there something in the ZIP file I didn't catch?

Thanks.

-Josh

**Comment by JoshHrach** [comment]
Okay, I was able to get this working by modifying the CMakeLists.txt file to include the directory with CMakeFunctions.cmake. Was this the appropriate solution?

**Comment by qdot** [comment]
I should really kill compily_buildd here like I have in other repos. I'll see about doing that soon.

**Comment by JoshHrach** [comment]
Oh, I was ready to kill it myself, personally. :)

I assume that, with my modification, it still got the job done? If I got no errors, I'm assuming it completed as intended?

**Comment by qdot** [comment]
Should be, yes. Sorry you had to suffer through my over-zealous build functions. :)

**Comment by JoshHrach** [comment]
That's alright. Took me a while to track it down, but I'm glad I did.

I suppose this ends this issue. I did email you today with an overall question about the Libomron project, though. Hope it didn't end up in spam!

Thanks again!
